// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionSection: typeof import('./src/components/ActionSection.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HowToNavigation: typeof import('./src/components/HowToNavigation.vue')['default']
    LatestNews: typeof import('./src/components/LatestNews.vue')['default']
    Locales: typeof import('./src/components/Locales.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NavigationChoice: typeof import('./src/components/NavigationChoice.vue')['default']
    NewsArticle: typeof import('./src/components/NewsArticle.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    NewsHeader: typeof import('./src/components/NewsHeader.vue')['default']
    NewsMiniCard: typeof import('./src/components/NewsMiniCard.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Section.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
  }
}

export { }
