// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionSection: typeof import('./components/ActionSection.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HowToNavigation: typeof import('./components/HowToNavigation.vue')['default']
    LatestAnnouncements: typeof import('./components/LatestAnnouncements.vue')['default']
    LatestNews: typeof import('./components/LatestNews.vue')['default']
    Locales: typeof import('./components/Locales.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    MarketCard: typeof import('./components/MarketCard.vue')['default']
    MarketForm: typeof import('./components/MarketForm.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NavigationChoice: typeof import('./components/NavigationChoice.vue')['default']
    NewsArticle: typeof import('./components/NewsArticle.vue')['default']
    NewsCard: typeof import('./components/NewsCard.vue')['default']
    NewsHeader: typeof import('./components/NewsHeader.vue')['default']
    NewsMiniCard: typeof import('./components/NewsMiniCard.vue')['default']
    OurMission: typeof import('./components/OurMission.vue')['default']
    Person: typeof import('./components/Person.vue')['default']
    Press: typeof import('./components/Press.vue')['default']
    Requirements: typeof import('./components/Requirements.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section.vue')['default']
    Socials: typeof import('./components/Socials.vue')['default']
  }
}

export { }
